<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Spider_Solitaire</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <StartupObject></StartupObject>
    <FileVersion>0.4.1.2</FileVersion>
    <AssemblyVersion>0.4.1.2</AssemblyVersion>
    <PackageLicenseFile>C:\Users\User\Desktop\da.txt</PackageLicenseFile>
    <Authors>apelsin</Authors>
    <Version>1.0</Version>
    <Copyright>Copyright (C) 2024 Project - All Rights Reserve</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\10a.png" />
    <None Remove="assets\10b.png" />
    <None Remove="assets\10c.png" />
    <None Remove="assets\10d.png" />
    <None Remove="assets\11a.png" />
    <None Remove="assets\11b.png" />
    <None Remove="assets\11c.png" />
    <None Remove="assets\11d.png" />
    <None Remove="assets\12a.png" />
    <None Remove="assets\12b.png" />
    <None Remove="assets\12c.png" />
    <None Remove="assets\12d.png" />
    <None Remove="assets\13a.png" />
    <None Remove="assets\13b.png" />
    <None Remove="assets\13c.png" />
    <None Remove="assets\13d.png" />
    <None Remove="assets\1a.png" />
    <None Remove="assets\1b.png" />
    <None Remove="assets\1c.png" />
    <None Remove="assets\1d.png" />
    <None Remove="assets\2a.png" />
    <None Remove="assets\2b.png" />
    <None Remove="assets\2c.png" />
    <None Remove="assets\2d.png" />
    <None Remove="assets\3a.png" />
    <None Remove="assets\3b.png" />
    <None Remove="assets\3c.png" />
    <None Remove="assets\3d.png" />
    <None Remove="assets\4a.png" />
    <None Remove="assets\4b.png" />
    <None Remove="assets\4c.png" />
    <None Remove="assets\4d.png" />
    <None Remove="assets\5a.png" />
    <None Remove="assets\5b.png" />
    <None Remove="assets\5c.png" />
    <None Remove="assets\5d.png" />
    <None Remove="assets\6a.png" />
    <None Remove="assets\6b.png" />
    <None Remove="assets\6c.png" />
    <None Remove="assets\6d.png" />
    <None Remove="assets\7a.png" />
    <None Remove="assets\7b.png" />
    <None Remove="assets\7c.png" />
    <None Remove="assets\7d.png" />
    <None Remove="assets\8a.png" />
    <None Remove="assets\8b.png" />
    <None Remove="assets\8c.png" />
    <None Remove="assets\8d.png" />
    <None Remove="assets\9a.png" />
    <None Remove="assets\9b.png" />
    <None Remove="assets\9c.png" />
    <None Remove="assets\9d.png" />
    <None Remove="assets\card_outline.png" />
    <None Remove="assets\greenbg.png" />
    <None Remove="assets\Logo.png" />
    <None Remove="assets\uncovered.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="assets\10a.png" />
    <Resource Include="assets\10b.png" />
    <Resource Include="assets\10c.png" />
    <Resource Include="assets\10d.png" />
    <Resource Include="assets\11a.png" />
    <Resource Include="assets\11b.png" />
    <Resource Include="assets\11c.png" />
    <Resource Include="assets\11d.png" />
    <Resource Include="assets\12a.png" />
    <Resource Include="assets\12b.png" />
    <Resource Include="assets\12c.png" />
    <Resource Include="assets\12d.png" />
    <Resource Include="assets\13a.png" />
    <Resource Include="assets\13b.png" />
    <Resource Include="assets\13c.png" />
    <Resource Include="assets\13d.png" />
    <Resource Include="assets\1a.png" />
    <Resource Include="assets\1b.png" />
    <Resource Include="assets\1c.png" />
    <Resource Include="assets\1d.png" />
    <Resource Include="assets\2a.png" />
    <Resource Include="assets\2b.png" />
    <Resource Include="assets\2c.png" />
    <Resource Include="assets\2d.png" />
    <Resource Include="assets\3a.png" />
    <Resource Include="assets\3b.png" />
    <Resource Include="assets\3c.png" />
    <Resource Include="assets\3d.png" />
    <Resource Include="assets\4a.png" />
    <Resource Include="assets\4b.png" />
    <Resource Include="assets\4c.png" />
    <Resource Include="assets\4d.png" />
    <Resource Include="assets\5a.png" />
    <Resource Include="assets\5b.png" />
    <Resource Include="assets\5c.png" />
    <Resource Include="assets\5d.png" />
    <Resource Include="assets\6a.png" />
    <Resource Include="assets\6b.png" />
    <Resource Include="assets\6c.png" />
    <Resource Include="assets\6d.png" />
    <Resource Include="assets\7a.png" />
    <Resource Include="assets\7b.png" />
    <Resource Include="assets\7c.png" />
    <Resource Include="assets\7d.png" />
    <Resource Include="assets\8a.png" />
    <Resource Include="assets\8b.png" />
    <Resource Include="assets\8c.png" />
    <Resource Include="assets\8d.png" />
    <Resource Include="assets\9a.png" />
    <Resource Include="assets\9b.png" />
    <Resource Include="assets\9c.png" />
    <Resource Include="assets\9d.png" />
    <Resource Include="assets\card_outline.png" />
    <Resource Include="assets\greenbg.png" />
    <Resource Include="assets\uncovered.png" />
  </ItemGroup>

</Project>
