<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="assets\10a.png" />
    <None Remove="assets\10b.png" />
    <None Remove="assets\10c.png" />
    <None Remove="assets\10d.png" />
    <None Remove="assets\11a.png" />
    <None Remove="assets\11b.png" />
    <None Remove="assets\11c.png" />
    <None Remove="assets\11d.png" />
    <None Remove="assets\12a.png" />
    <None Remove="assets\12b.png" />
    <None Remove="assets\12c.png" />
    <None Remove="assets\12d.png" />
    <None Remove="assets\13a.png" />
    <None Remove="assets\13b.png" />
    <None Remove="assets\13c.png" />
    <None Remove="assets\13d.png" />
    <None Remove="assets\1a.png" />
    <None Remove="assets\1b.png" />
    <None Remove="assets\1c.png" />
    <None Remove="assets\1d.png" />
    <None Remove="assets\2a.png" />
    <None Remove="assets\2b.png" />
    <None Remove="assets\2c.png" />
    <None Remove="assets\2d.png" />
    <None Remove="assets\3a.png" />
    <None Remove="assets\3b.png" />
    <None Remove="assets\3c.png" />
    <None Remove="assets\3d.png" />
    <None Remove="assets\4a.png" />
    <None Remove="assets\4b.png" />
    <None Remove="assets\4c.png" />
    <None Remove="assets\4d.png" />
    <None Remove="assets\5a.png" />
    <None Remove="assets\5b.png" />
    <None Remove="assets\5c.png" />
    <None Remove="assets\5d.png" />
    <None Remove="assets\6a.png" />
    <None Remove="assets\6b.png" />
    <None Remove="assets\6c.png" />
    <None Remove="assets\6d.png" />
    <None Remove="assets\7a.png" />
    <None Remove="assets\7b.png" />
    <None Remove="assets\7c.png" />
    <None Remove="assets\7d.png" />
    <None Remove="assets\8a.png" />
    <None Remove="assets\8b.png" />
    <None Remove="assets\8c.png" />
    <None Remove="assets\8d.png" />
    <None Remove="assets\9a.png" />
    <None Remove="assets\9b.png" />
    <None Remove="assets\9c.png" />
    <None Remove="assets\9d.png" />
    <None Remove="assets\home_icon_pressed.png" />
    <None Remove="assets\home_icon_unpressed.png" />
    <None Remove="assets\uncovered.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="assets\10a.png" />
    <EmbeddedResource Include="assets\10b.png" />
    <EmbeddedResource Include="assets\10c.png" />
    <EmbeddedResource Include="assets\10d.png" />
    <EmbeddedResource Include="assets\11a.png" />
    <EmbeddedResource Include="assets\11b.png" />
    <EmbeddedResource Include="assets\11c.png" />
    <EmbeddedResource Include="assets\11d.png" />
    <EmbeddedResource Include="assets\12a.png" />
    <EmbeddedResource Include="assets\12b.png" />
    <EmbeddedResource Include="assets\12c.png" />
    <EmbeddedResource Include="assets\12d.png" />
    <EmbeddedResource Include="assets\13a.png" />
    <EmbeddedResource Include="assets\13b.png" />
    <EmbeddedResource Include="assets\13c.png" />
    <EmbeddedResource Include="assets\13d.png" />
    <EmbeddedResource Include="assets\1a.png" />
    <EmbeddedResource Include="assets\1b.png" />
    <EmbeddedResource Include="assets\1c.png" />
    <EmbeddedResource Include="assets\1d.png" />
    <EmbeddedResource Include="assets\2a.png" />
    <EmbeddedResource Include="assets\2b.png" />
    <EmbeddedResource Include="assets\2c.png" />
    <EmbeddedResource Include="assets\2d.png" />
    <EmbeddedResource Include="assets\3a.png" />
    <EmbeddedResource Include="assets\3b.png" />
    <EmbeddedResource Include="assets\3c.png" />
    <EmbeddedResource Include="assets\3d.png" />
    <EmbeddedResource Include="assets\4a.png" />
    <EmbeddedResource Include="assets\4b.png" />
    <EmbeddedResource Include="assets\4c.png" />
    <EmbeddedResource Include="assets\4d.png" />
    <EmbeddedResource Include="assets\5a.png" />
    <EmbeddedResource Include="assets\5b.png" />
    <EmbeddedResource Include="assets\5c.png" />
    <EmbeddedResource Include="assets\5d.png" />
    <EmbeddedResource Include="assets\6a.png" />
    <EmbeddedResource Include="assets\6b.png" />
    <EmbeddedResource Include="assets\6c.png" />
    <EmbeddedResource Include="assets\6d.png" />
    <EmbeddedResource Include="assets\7a.png" />
    <EmbeddedResource Include="assets\7b.png" />
    <EmbeddedResource Include="assets\7c.png" />
    <EmbeddedResource Include="assets\7d.png" />
    <EmbeddedResource Include="assets\8a.png" />
    <EmbeddedResource Include="assets\8b.png" />
    <EmbeddedResource Include="assets\8c.png" />
    <EmbeddedResource Include="assets\8d.png" />
    <EmbeddedResource Include="assets\9a.png" />
    <EmbeddedResource Include="assets\9b.png" />
    <EmbeddedResource Include="assets\9c.png" />
    <EmbeddedResource Include="assets\9d.png" />
    <EmbeddedResource Include="assets\home_icon_pressed.png" />
    <EmbeddedResource Include="assets\home_icon_unpressed.png" />
    <EmbeddedResource Include="assets\uncovered.png" />
  </ItemGroup>

</Project>
